#!/bin/bash

python3 ech2o_multitools.py --file=def_DREAMcalib_seq.py --cfg=config_example_DREAMcalib --outdir=Output_DREAM_seq

#mpirun -c 21 python3 ech2o_multitools.py --file=def_DREAMcalib_mpi.py --cfg=config_example_DREAMcalib --outdir=Output_DREAM_mpi
