#!/bin/sh

# Names of job, outputs....
#SBATCH --job-name=MorrisEcH2O
#SBATCH -o jobs_out/MorrisEcH2O_%j.out # STDOUT
#SBATCH -e jobs_out/MorrisEcH2O_%j.err # STDERR

# Partition
#SBATCH -w n401
#SBATCH -p get
# SBATCH -p omp_parall
# Communicating
# SBATCH -A U_RIVERLY
#SBATCH --mail-type=END
#SBATCH --mail-user=sylvain.kuppel@ird.fr
# NUmber of nodes and MPI task per nodes
# SBATCH --nodes=1
#SBATCH --ntasks=1
# SBATCH --ntasks-per-node=1
# -not used- SBATCH --ntasks-per-socket=1
# -not used/needed- SBATCH --sockets-per-node=2
# -not used- SBATCH --cores-per-socket=12
# For OpenMP:
#SBATCH --cpus-per-task=1
# SBATCH --mem-per-cpu=1GB

# Wall clock limit:
# SBATCH --time=48:00:00
# SBATCH --mem=10000

#SBATCH --export=ALL

echo ${SLURM_JOB_NODELIST}
#cd ${SLURM_SUBMIT_DIR}
echo ${SLURM_SUBMIT_DIR}

# For pinning threads correctly:
export OMP_PLACES=threads
#export OMP_PROC_BIND=spread

# Using conda for pcraster
source /home/sila/miniconda3/etc/profile.d/conda.sh
conda deactivate
conda activate pcraster39

cd /home/kups/runs/ech2o/MuleHole/

#python3 -i ech2o_multitools.py --file=def_morris_90m_nospin.py  --cfg=config_90m_nospin_Ts  --cfgTrck=configTrck_Ts --outdir=Morris_90m_nospin
#python3 -i ech2o_multitools.py --file=def_morris_90m_nospin.py  --cfg=config_90m_nospin_Ts  --cfgTrck=configTrck_Ts --outdir=Morris_90m_nospin_short

#python3 -i ech2o_multitools.py --file=def_morris_90m_spin12Y.py  --cfg=config_90m_spin12Y_Ts  --cfgTrck=configTrck_spin12Y_Ts --outdir=Morris_90m_spin12Y --ncpu=$SLURM_CPUS_PER_TASK
#python3 -i ech2o_multitools.py --file=def_morris_90m_28Y.py  --cfg=config_90m_28Y_Ts  --cfgTrck=configTrck_28Y_Ts --outdir=Morris_90m_28Y --ncpu=$SLURM_CPUS_PER_TASK

#python -u ech2o_multitools.py --file=def_morris_90m_1997-2019_Ts.py  --cfg=config_90m_1997-2019_Ts_morris  --cfgTrck=configTrck_1997-2019_Ts_morris --outdir=Morris_90m_1997-2019_rs3 --ncpu=12

#python -u ech2o_multitools.py --file=def_morris_90m_1997-2019.py  --cfg=config_90m_1997-2019_morris_rs3 --cfgTrck=configTrck_1997-2019_morris --outdir=Morris_90m_1997-2019_rs3 --ncpu=12 --scratch=0
#python -u ech2o_multitools.py --file=def_morris_90m_1997-2019.py  --cfg=config_90m_1997-2019_morris_rs3 --cfgTrck=configTrck_1997-2019_morris --outdir=Morris_90m_1997-2019_rs3 --ncpu=$SLURM_CPUS_PER_TASK --scratch=1
#python -u ech2o_multitools.py --file=def_morris_90m_1997-2019.py  --cfg=config_90m_1997-2019_morris_rs2 --cfgTrck=configTrck_1997-2019_morris --outdir=Morris_90m_1997-2019_rs2 --ncpu=$SLURM_CPUS_PER_TASK --scratch=1

#python3 -i ech2o_multitools.py --file=def_morris_test.py  --cfg=config_90m_1997-2019_Ts_morris  --cfgTrck=configTrck_1997-2019_Ts_morris --outdir=Morris_test --ncpu=1

#python3 -u ech2o_multitools.py --file=def_morris_P5_1997-2019_Ts.py  --cfg=config_P5_1997-2019_Ts  --cfgTrck=configTrck_1997-2019_Ts --outdir=Morris_P5_1997-2019_fRWU_rs3 --ncpu=1 --scratch=1
#python3 -i ech2o_multitools.py --file=def_morris_P5_1997-2019_Ts.py  --cfg=config_P5_1997-2019_Ts_rs2  --cfgTrck=configTrck_1997-2019_Ts --outdir=Morris_P5_1997-2019_fRWU_rs2 --ncpu=1 --scratch=1

#python -u ech2o_multitools.py --file=def_morris_P5_1997-2023.py  --cfg=config_P5_1997-2023_morris      --cfgTrck=configTrck_1997-2023_morris --outdir=Morris_P5_1997-2023_rs3 --ncpu=1 --scratch=1
#python -u ech2o_multitools.py --file=def_morris_P5_1997-2023.py  --cfg=config_P5_1997-2023_morris_rs2  --cfgTrck=configTrck_1997-2023_morris --outdir=Morris_P5_1997-2023_rs2 --ncpu=1 --scratch=1
#python -u ech2o_multitools.py --file=def_morris_P5_1997-2023_hydroVH.py  --cfg=config_P5_1997-2023_morris      --cfgTrck=configTrck_1997-2023_morris --outdir=Morris_P5_1997-2023_rs3_hydroVH --ncpu=1 --scratch=1
python -i ech2o_multitools.py --file=def_morris_P5_1997-2023.py  --SA_init=1 --outdir=Morris1_P5 
python -i ech2o_multitools.py --file=def_morris_P5_1997-2023.py  --SA_init=0 --cfg=config_P5_1997-2023_morris --cfgTrck=configTrck_1997-2023_morris --ncpu=1 --outdir=Morris1_P5 --task=Morris1_P5.1 #--scratch=1
#python -u ech2o_multitools.py --file=def_morris_P5_1997-2023_hydroVH.py  --cfg=config_P5_1997-2023_morris_rs2  --cfgTrck=configTrck_1997-2023_morris --outdir=Morris_P5_1997-2023_rs2_hydroVH --ncpu=1 --scratch=1

