#!/bin/bash

# If SA_init = 1, i.e. generating parameters values for trajectories/radial points in a given directory (Sensitivity_ParameterSets in this example)

python -i main.py --file=def_SensiMorris.py  --SA_init=1 --outdir=Morris1_P5

# If SA_init = 0, i.e. running the model along trajectory/radial points

#python -i main.py --file=def_SensiMorris.py  --SA_init=0 --cfg=config_example_sensi --cfgTrck=configTrck_example_sensi --ncpu=1 --outdir=Morris1_P5 --task=Morris1_P5.1 #--scratch=1
#python -i main.py --file=def_SensiMorris.py  --SA_init=0 --cfg=config_example_sensi --cfgTrck=configTrck_example_sensi --ncpu=1 --outdir=Morris1_P5 --task=Morris1_P5.2 #--scratch=1
#python -i main.py --file=def_SensiMorris.py  --SA_init=0 --cfg=config_example_sensi --cfgTrck=configTrck_example_sensi --ncpu=1 --outdir=Morris1_P5 --task=Morris1_P5.3 #--scratch=1
#python -i main.py --file=def_SensiMorris.py  --SA_init=0 --cfg=config_example_sensi --cfgTrck=configTrck_example_sensi --ncpu=1 --outdir=Morris1_P5 --task=Morris1_P5.4 #--scratch=1
